### PR TITLE
Add template name to template response models

### PR DESCRIPTION
**Pull request by connor-walker**
The public api has a pull request to include the name in template responses, this pull request adds the name property to the template response models so the new data is used.

Also, ignore the duplicate commit reference earlier, I hadn't set the email config on this machine... 🙂

### CODE REVIEW

**Comment by quis** [comment]
Depends on:
- [ ] https://github.com/alphagov/notifications-api/pull/1180

**Comment by imdadahad** [comment]
Hi @connor-walker,

Thanks for contributing, you beat us to it with this change.

Could you possibly add an extra line in the integration tests that asserts the name exists in the response. You can find the method here which already checks that the expected fields in the template response exist: https://github.com/alphagov/notifications-net-client/blob/0ad24938b46695342940b0dd9623df36892cc755/NotifyTests/IntegrationTests/NotificationIntegrationClientTests.cs#L308

**Comment by connor-walker** [comment]
Hi @imdadahad,

My apologies, I've only just had chance to make that change. Let me know if anything else needs changing!

**Comment by leohemsted** [comment]
ok to test

**Comment by leohemsted** [comment]
ok to test

**Comment by imdadahad** [comment]
Thanks @connor-walker, tests have passed so all okay to merge in.

**Pull request merged**
