### PR TITLE
Implemented asynchronous version of Notify API

### PR DESCRIPTION
**Pull request by david-preston-triad**
## What problem does the pull request solve?

The current implementation of the API Client is synchronous.  This was causing bottlenecks during our load testing (which sends lots of messages using Notify).  We modified the code to make the API Client methods asynchronous as part of measures to improve the performance of our system.  We would like to share these changes with you, as they may be useful for other projects.

## Checklist

- [x] I’ve used the pull request template
- [x] I’ve written unit tests for these changes
- [ ] I’ve update the documentation (in `DOCUMENTATION.md` and `CHANGELOG.md`)
- [x] I’ve bumped the version number (in `src/Notify/Notify.csproj`)

I have updated CHANGELOG.md but not DOCUMENTATION.md.  Should I duplicate all the descriptions of the synchronous methods to describe their asynchronous counterparts?  Or is it better to add a footnote to say that asynchronous versions of the methods are available?

### CODE REVIEW

**Comment by quis** [comment]
@david-preston-triad This is an awesome effort, thank you so much. It might take us a bit of time to find someone knowledgeable in .NET to review this, but in principle we’re in favour of it (some of our other clients work asynchronously). 

Two quick questions:
- is this a breaking change for existing users?
- does this change the versions of .NET supported by this client?

**Comment by quis** [comment]
@govuk-notify-jenkins test this please

**Comment by david-preston-triad** [comment]
@quis You're very welcome.  To answer your questions:
* No, this change should not break code for existing users (I have kept the original, synchronous, unit tests and these still run OK).
* No, this does not change the versions of .NET supported by the client (I kept the version of the project at .NET Framework 4.6.2).

**Comment by mtallamy** [comment]
Morning. We'd really like to use this change in our service. Are you able to give us an idea of when this will be merged and made available through NuGet?

Many thanks.

**Comment by servingUpAces** [comment]
@mtallamy @david-preston-triad This has been merged and is available on bintray in version 2.5.0.

**Pull request merged**
